# Generated by Django 5.2.1 on 2025-06-05 23:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="User's full name (minimum 2 characters)", max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('email', models.EmailField(help_text="User's email address (must be unique)", max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['email'], name='api_user_email_a7eefd_idx'), models.Index(fields=['created_at'], name='api_user_created_f8e07b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Task title (minimum 3 characters)', max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(blank=True, help_text='Detailed task description')),
                ('completed', models.BooleanField(default=False, help_text='Task completion status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Task priority level', max_length=10)),
                ('due_date', models.DateTimeField(blank=True, help_text='Task due date and time', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the task was completed', null=True)),
                ('user', models.ForeignKey(help_text='Task owner', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.user')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-priority', 'due_date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'completed'], name='api_task_user_id_5e79a6_idx'), models.Index(fields=['due_date'], name='api_task_due_dat_54ead5_idx'), models.Index(fields=['priority'], name='api_task_priorit_175238_idx'), models.Index(fields=['created_at'], name='api_task_created_9da793_idx')],
            },
        ),
    ]
